baseURL = "https://maofriend.com/"
title   = "maofriend"
languageCode = 'en-us'
theme   = "hugo-geekdoc"
paginate = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  enableRobotsTXT = true

  geekdocBackToTop = false


  # geekdocPrivacyPolicy = "/privacy"
  geekdocOverwriteHTMLBase = false


  # geekdocLegalNotice = "https://blog.example.com/legal"


[params.geekdocContentLicense]
  name = "粤ICP备2021164354号-1"
  link = "https://beian.miit.gov.cn <a>"

[taxonomies]
  tag = "tags"
